/***********************************************************************************
	Copyright 2006. Akshay Mishra	

	This file is part of WaveVIZ.

	WaveVIZ is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.
	
	WaveVIZ is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License
	along with WaveVIZ; if not, write to the Free Software
	Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
************************************************************************************/	
// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "WaveVizUI.h"

void WaveVizUI::cb_vrot_i(Fl_Roller* o, void*) {
  app->m_renderer->phi=-((Fl_Roller *)o)->value();
}
void WaveVizUI::cb_vrot(Fl_Roller* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->parent()->user_data()))->cb_vrot_i(o,v);
}

void WaveVizUI::cb_hrot_i(Fl_Roller* o, void*) {
  app->m_renderer->theta=-((Fl_Roller *)o)->value();
}
void WaveVizUI::cb_hrot(Fl_Roller* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->parent()->user_data()))->cb_hrot_i(o,v);
}

void WaveVizUI::cb_zoom_i(Fl_Slider* o, void*) {
  app->m_renderer->m_camera->Eye.z=-((Fl_Slider *)o)->value();
app->m_renderer->UpdateCamera();
}
void WaveVizUI::cb_zoom(Fl_Slider* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->user_data()))->cb_zoom_i(o,v);
}

void WaveVizUI::cb_btnCompute_i(Fl_Light_Button* o, void*) {
  app->m_renderer->compute=((Fl_Light_Button *)o)->value();
app->m_genfunc();
}
void WaveVizUI::cb_btnCompute(Fl_Light_Button* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->user_data()))->cb_btnCompute_i(o,v);
}

void WaveVizUI::cb_btnSetDensity_i(Fl_Button*, void*) {
  app->m_renderer->m_startdensity = 40*atof (txtstartdensity->value());
app->m_renderer->m_enddensity = 40*atof (txtenddensity->value());
app->m_renderer->m_cubesize=atoi (txtcubesize->value());
}
void WaveVizUI::cb_btnSetDensity(Fl_Button* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->user_data()))->cb_btnSetDensity_i(o,v);
}

void WaveVizUI::cb_btnreset_i(Fl_Button*, void*) {
  app->m_renderer->t=0;
}
void WaveVizUI::cb_btnreset(Fl_Button* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->user_data()))->cb_btnreset_i(o,v);
}

void WaveVizUI::cb_radHarmonic_i(Fl_Round_Button* o, void*) {
  if(((Fl_Check_Button *)o)->value())
{
	grpHarmonic->activate();
	grpBox->deactivate();
	grponeelectron->deactivate();
}
else
{
	grpHarmonic->deactivate();
};
}
void WaveVizUI::cb_radHarmonic(Fl_Round_Button* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->user_data()))->cb_radHarmonic_i(o,v);
}

void WaveVizUI::cb_radBox_i(Fl_Round_Button* o, void*) {
  if(((Fl_Check_Button *)o)->value())
{
	grpHarmonic->deactivate();
	grpBox->activate();
	grponeelectron->deactivate();
}
else
{
	grpBox->deactivate();
};
}
void WaveVizUI::cb_radBox(Fl_Round_Button* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->user_data()))->cb_radBox_i(o,v);
}

void WaveVizUI::cb_radOneElectron_i(Fl_Round_Button* o, void*) {
  if(((Fl_Check_Button *)o)->value())
{
	grpHarmonic->deactivate();
	grpBox->deactivate();
	grponeelectron->activate();
}
else
{
	grponeelectron->deactivate();
};
}
void WaveVizUI::cb_radOneElectron(Fl_Round_Button* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->user_data()))->cb_radOneElectron_i(o,v);
}

void WaveVizUI::cb_chkmorph_i(Fl_Check_Button* o, void*) {
  if(((Fl_Check_Button *)o)->value())
{
	grpmorph->activate();
}
else
{
	grpmorph->deactivate();
};
}
void WaveVizUI::cb_chkmorph(Fl_Check_Button* o, void* v) {
  ((WaveVizUI*)(o->parent()->parent()->user_data()))->cb_chkmorph_i(o,v);
}

WaveVizUI::WaveVizUI() {
  Fl_Window* w;
  { Fl_Window* o = mainWindow = new Fl_Window(1115, 895, "WaveVIZ - Quantum Wavefunction Visualizer");
    w = o;
    o->box(FL_UP_BOX);
    o->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(15, 160, 745, 720);
      o->box(FL_ENGRAVED_FRAME);
      { Fl_Group* o = VChange = new Fl_Group(35, 365, 55, 450);
        { Fl_Roller* o = vrot = new Fl_Roller(55, 435, 15, 180, "Rotate-X");
          o->minimum(-180);
          o->maximum(180);
          o->step(1);
          o->callback((Fl_Callback*)cb_vrot);
        }
        o->end();
      }
      { Fl_Group* o = HChange = new Fl_Group(295, 835, 210, 20);
        { Fl_Roller* o = hrot = new Fl_Roller(305, 840, 190, 15, "Rotate about Y");
          o->type(1);
          o->minimum(-180);
          o->maximum(180);
          o->step(1);
          o->callback((Fl_Callback*)cb_hrot);
        }
        o->end();
      }
      { Fl_Group* o = MainView = new Fl_Group(100, 245, 620, 588);
        o->box(FL_EMBOSSED_FRAME);
        { CApplication* o = app = new CApplication(105, 251, 610, 578);
          o->box(FL_THIN_DOWN_BOX);
          o->color(FL_BACKGROUND_COLOR);
          o->selection_color(FL_BACKGROUND_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->align(FL_ALIGN_CENTER);
          o->when(FL_WHEN_RELEASE);
        }
        o->end();
      }
      { Fl_Slider* o = zoom = new Fl_Slider(100, 195, 230, 20, "Distance from origin");
        o->type(1);
        o->box(FL_PLASTIC_THIN_DOWN_BOX);
        o->minimum(-2000);
        o->maximum(500);
        o->step(1);
        o->slider_size(0.060606);
        o->callback((Fl_Callback*)cb_zoom);
      }
      { Fl_Light_Button* o = btnCompute = new Fl_Light_Button(540, 840, 180, 30, "Compute Wavefunction");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->selection_color((Fl_Color)93);
        o->callback((Fl_Callback*)cb_btnCompute);
      }
      txtstartdensity = new Fl_Input(490, 176, 50, 24, "Start density:");
      txtenddensity = new Fl_Input(635, 176, 40, 24, "End Density:");
      { Fl_Button* o = btnSetDensity = new Fl_Button(550, 210, 170, 25, "Set Density && Cube size");
        o->callback((Fl_Callback*)cb_btnSetDensity);
      }
      { Fl_Button* o = btnreset = new Fl_Button(145, 840, 105, 30, "Reset Time");
        o->callback((Fl_Callback*)cb_btnreset);
      }
      txtcubesize = new Fl_Input(490, 211, 50, 24, "Cube-size:");
      o->end();
    }
    { Fl_Group* o = grpSelector = new Fl_Group(775, 175, 320, 235, "Select Eigenfunction:");
      o->box(FL_ENGRAVED_FRAME);
      o->align(FL_ALIGN_TOP_LEFT);
      { Fl_Round_Button* o = radHarmonic = new Fl_Round_Button(800, 205, 155, 15, "Harmonic Oscillator");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*)cb_radHarmonic);
      }
      { Fl_Round_Button* o = radBox = new Fl_Round_Button(800, 240, 135, 15, "Particle-in-a-box");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*)cb_radBox);
      }
      { Fl_Round_Button* o = radOneElectron = new Fl_Round_Button(800, 275, 150, 15, "One - electron atom");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*)cb_radOneElectron);
      }
      { Fl_Check_Button* o = chkmorph = new Fl_Check_Button(800, 305, 95, 20, "Morph");
        o->down_box(FL_DOWN_BOX);
        o->callback((Fl_Callback*)cb_chkmorph);
      }
      txtmorph = new Fl_Input(1010, 301, 35, 24, "Morph time (frames):");
      { Fl_Group* o = grpmorph = new Fl_Group(800, 330, 125, 70);
        o->box(FL_ENGRAVED_FRAME);
        o->deactivate();
        { Fl_Round_Button* o = radmorph12 = new Fl_Round_Button(820, 345, 105, 15, "1-->2");
          o->type(102);
          o->down_box(FL_ROUND_DOWN_BOX);
        }
        { Fl_Round_Button* o = radmorph21 = new Fl_Round_Button(820, 370, 105, 15, "2-->1");
          o->type(102);
          o->down_box(FL_ROUND_DOWN_BOX);
        }
        o->end();
      }
      o->end();
    }
    { Fl_Group* o = grpHarmonic = new Fl_Group(775, 520, 320, 75, "Harmonic oscillator parameters:");
      o->box(FL_ENGRAVED_FRAME);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
      txtw1 = new Fl_Input(890, 546, 20, 24, "n1:");
      txtw2 = new Fl_Input(940, 546, 20, 24, "n2:");
      txtw3 = new Fl_Input(995, 546, 20, 24, "n3:");
      txtw0 = new Fl_Input(825, 546, 30, 24, "w0:");
      txtw4 = new Fl_Input(1045, 546, 20, 24, "n4:");
      o->end();
    }
    { Fl_Group* o = grpBox = new Fl_Group(775, 620, 325, 120, "Particle-in-a-box parameters:");
      o->box(FL_ENGRAVED_FRAME);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
      txtlx = new Fl_Input(810, 642, 30, 21, "Lx:");
      txtly = new Fl_Input(810, 672, 30, 23, "Ly:");
      txtlz = new Fl_Input(810, 701, 30, 24, "Lz:");
      txtnx1 = new Fl_Input(880, 640, 20, 24, "nx1:");
      txtny1 = new Fl_Input(880, 671, 20, 24, "ny1:");
      txtnz1 = new Fl_Input(880, 701, 20, 24, "nz1:");
      txtnx2 = new Fl_Input(940, 640, 20, 24, "nx2:");
      txtny2 = new Fl_Input(940, 671, 20, 24, "ny2:");
      txtnz2 = new Fl_Input(940, 701, 20, 24, "nz2:");
      txtnx3 = new Fl_Input(1000, 640, 20, 24, "nx3:");
      txtny3 = new Fl_Input(1000, 671, 20, 24, "ny3:");
      txtnz3 = new Fl_Input(1000, 701, 20, 24, "nz3:");
      txtnx4 = new Fl_Input(1060, 642, 20, 23, "nx4:");
      txtny4 = new Fl_Input(1060, 672, 20, 23, "ny4:");
      txtnz4 = new Fl_Input(1060, 702, 20, 23, "nz4:");
      o->end();
    }
    { Fl_Group* o = grponeelectron = new Fl_Group(775, 765, 320, 115, "1-electron atom parameters:");
      o->box(FL_ENGRAVED_FRAME);
      o->align(FL_ALIGN_TOP_LEFT);
      o->deactivate();
      txtz = new Fl_Input(800, 781, 25, 24, "Z:");
      txtn1 = new Fl_Input(855, 781, 25, 24, "n1:");
      txtl1 = new Fl_Input(855, 811, 25, 24, "l1:");
      txtm1 = new Fl_Input(855, 841, 25, 24, "m1:");
      txtn2 = new Fl_Input(925, 781, 25, 24, "n2:");
      txtl2 = new Fl_Input(925, 811, 25, 24, "l2:");
      txtm2 = new Fl_Input(925, 841, 25, 24, "m2:");
      txtn3 = new Fl_Input(1000, 781, 25, 24, "n3:");
      txtl3 = new Fl_Input(1000, 811, 25, 24, "l3:");
      txtm3 = new Fl_Input(1000, 841, 25, 24, "m3:");
      txtn4 = new Fl_Input(1060, 781, 25, 24, "n4:");
      txtl4 = new Fl_Input(1060, 811, 25, 24, "l4:");
      txtm4 = new Fl_Input(1060, 841, 25, 24, "m4:");
      o->end();
    }
    { Fl_Group* o = grpsuperpose = new Fl_Group(775, 435, 320, 60, "Select functions to superpose:");
      o->box(FL_ENGRAVED_FRAME);
      o->align(FL_ALIGN_TOP_LEFT);
      { Fl_Check_Button* o = chkwave2 = new Fl_Check_Button(890, 460, 30, 15, "2");
        o->down_box(FL_DOWN_BOX);
      }
      { Fl_Check_Button* o = chkwave3 = new Fl_Check_Button(965, 460, 30, 15, "3");
        o->down_box(FL_DOWN_BOX);
      }
      { Fl_Check_Button* o = chkwave4 = new Fl_Check_Button(1025, 460, 30, 15, "4");
        o->down_box(FL_DOWN_BOX);
      }
      { Fl_Check_Button* o = chkwave1 = new Fl_Check_Button(825, 460, 30, 15, "1");
        o->down_box(FL_DOWN_BOX);
      }
      o->end();
    }
    { Fl_Group* o = grpstate1 = new Fl_Group(445, 35, 315, 110, "State 1 coefficients:");
      o->box(FL_ENGRAVED_FRAME);
      o->align(FL_ALIGN_TOP_LEFT);
      txtre11 = new Fl_Input(490, 61, 30, 24, "Re1:");
      txtre12 = new Fl_Input(560, 61, 30, 24, "Re2:");
      txtre13 = new Fl_Input(630, 61, 30, 24, "Re3:");
      txtre14 = new Fl_Input(705, 61, 30, 24, "Re4:");
      txtim11 = new Fl_Input(490, 96, 30, 24, "Im1:");
      txtim12 = new Fl_Input(560, 96, 30, 24, "Im2:");
      txtim13 = new Fl_Input(630, 96, 30, 24, "Im3:");
      txtim14 = new Fl_Input(705, 96, 30, 24, "Im4:");
      o->end();
    }
    { Fl_Group* o = grpstate2 = new Fl_Group(775, 35, 320, 110, "State 2 coefficients:");
      o->box(FL_ENGRAVED_FRAME);
      o->align(FL_ALIGN_TOP_LEFT);
      txtre21 = new Fl_Input(825, 61, 30, 24, "Re1:");
      txtre22 = new Fl_Input(895, 61, 30, 24, "Re2:");
      txtre23 = new Fl_Input(965, 61, 30, 24, "Re3:");
      txtre24 = new Fl_Input(1040, 61, 30, 24, "Re4:");
      txtim21 = new Fl_Input(825, 96, 30, 24, "Im1:");
      txtim22 = new Fl_Input(895, 96, 30, 24, "Im2:");
      txtim23 = new Fl_Input(965, 96, 30, 24, "Im3:");
      txtim24 = new Fl_Input(1040, 96, 30, 24, "Im4:");
      o->end();
    }
    { Fl_Button* o = new Fl_Button(15, 20, 420, 125, "WaveVIZ - Wavefunction Visualization Tool");
      o->box(FL_PLASTIC_THIN_UP_BOX);
      o->down_box(FL_PLASTIC_THIN_UP_BOX);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(20);
      o->labelcolor((Fl_Color)186);
    }
    o->end();
  }
}

void WaveVizUI::show(int argc, char **argv, PCOMPFUNC ptr) {
  mainWindow->show(argc, argv);
app->make_current();
app->InitApplication (ptr);
app->show();
}
